baseURL = "https://jdkang.github.io/"
languageCode = "en-us"
title = "a canticle for devops"
theme = "hugo-dusk"
canonifyurls = true
SectionPagesMenu = "main"

[author]
  name = "Jai Kang"

# Configure syntax highlight
[markup]
  [markup.highlight]
    style = "rrt" # dark themes: monokai, api, fruity, native, rrt, swapoff

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "posts"
  url = "/posts/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[[menu.main]]
  name = "About"
  weight = -100
  identifier = "about"
  url = "/about/"

[params.meta]
  keywords = "blog, tech, sre, devops"
  description = "jaigene kang blog"

[params]
  github = "jdkang"
  linkedin = "jaigene-kang/"